import os
import pandas as pd
import mysql.connector

# --- DATABASE CONFIG ---
DB_CONFIG = {
    "host":     "localhost",
    "user":     "daria",
    "password": os.getenv("DB_PASSWORD", ""),
    "database": "brain_multiomics"
}

def upload_genes(csv_file):
    # 1. Load the CSV generated by your R script
    df = pd.read_csv(csv_file)
    # Your R script names the column 'Gene'
    gene_list = df['Gene'].dropna().unique().tolist()
    
    conn = mysql.connector.connect(**DB_CONFIG)
    cursor = conn.cursor()

    # 2. Create the table if it doesn't exist
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS plasticity_genes (
            gene_symbol VARCHAR(50) PRIMARY KEY
        )
    """)

    # 3. Insert the genes
    print(f"Uploading {len(gene_list)} genes from R script to MySQL...")
    sql = "INSERT IGNORE INTO plasticity_genes (gene_symbol) VALUES (%s)"
    data = [(str(g).upper().strip(),) for g in gene_list]
    
    cursor.executemany(sql, data)
    conn.commit()
    
    cursor.close()
    conn.close()
    print("✓ Plasticity gene table updated!")

if __name__ == "__main__":
    upload_genes("plasticity_genes.csv")