#!/usr/bin/env python3
"""
Read clean_metadata_GSE102538.csv and generate a SQL file with INSERT IGNORE statements
for `metadata_import` and `samples`. Output: data/chip_GSE102538 /clean_metadata_GSE102538.sql
"""
import csv
import os

csv_path = os.path.join('data', 'chip_GSE102538 ', 'clean_metadata_GSE102538.csv')
sql_path = os.path.join('data', 'chip_GSE102538 ', 'clean_metadata_GSE102538.sql')

rows = []
with open(csv_path, newline='') as fh:
    reader = csv.DictReader(fh)
    for r in reader:
        rows.append(r)

with open(sql_path, 'w') as fh:
    fh.write('-- SQL generated by generate_chip_metadata_sql.py\n')
    fh.write('USE brain_multiomics;\n')
    for r in rows:
        sample_id = r['sample_id'].replace("'", "''")
        dataset = r['dataset'].replace("'", "''")
        organism = r['organism_ch1'].replace("'", "''")
        tissue = r['source_name_ch1'].replace("'", "''")
        sex = r.get('sex','').replace("'", "''")
        age = r.get('age','').replace("'", "''")
        condition = r.get('condition','').replace("'", "''")

        # metadata_import insert
        fh.write("INSERT IGNORE INTO metadata_import (sample_id, dataset, organism, condition, tissue, sex, age) VALUES ('{}','{}','{}','{}','{}','{}','{}');\n".format(
            sample_id, dataset, organism, condition, tissue, sex, age
        ))

        # samples insert
        fh.write("INSERT IGNORE INTO samples (sample_id, `condition`, tissue, dataset) VALUES ('{}','{}','{}','{}');\n".format(
            sample_id, condition, tissue, dataset
        ))

print('Wrote SQL to', sql_path)
